### B)

In [17]:
# toffanetto

import numpy as np
import matplotlib.pyplot as plt



In [18]:
class tf:
    def __init__(self, x, y, z, phi, theta, psi):
        self.x = x
        self.y = y
        self.z = z 
        self.phi = np.deg2rad(phi)
        self.theta = np.deg2rad(theta)
        self.psi = np.deg2rad(psi)
        
        self.t = np.array([[x, y ,z]]).T
        
    def getPoint(self,p1):
        Rx = np.array([[1, 0, 0], [0, np.cos(self.psi), np.sin(self.psi)], [0, -np.sin(self.psi), np.cos(self.psi)]])
        Ry = np.array([[np.cos(self.theta), 0, -np.sin(self.theta)], [0, 1, 0], [np.sin(self.theta), 0, np.cos(self.theta)]])
        Rz = np.array([[np.cos(self.phi), np.sin(self.phi), 0], [-np.sin(self.phi), np.cos(self.phi), 0], [0, 0, 1]])
        R = np.matmul(Rz,np.matmul(Ry,Rx))
        
        p2 = np.matmul(R,p1) + self.t
        return p2



In [19]:
p1 = np.array([[1, 2 ,3]]).T

p1_to_p2_TF = tf(x=1, y=2, z=15, phi=2, theta=1, psi=2)

p2 = p1_to_p2_TF.getPoint(p1=p1)
print('p2 = \n'+str(p2))

p2 = 
[[ 2.02157298]
 [ 4.06908819]
 [17.94537989]]


---
### C)

In [20]:
f = 0.05

q1x = p1[0][0]*(f/p1[2][0])
q1y = p1[1][0]*(f/p1[2][0])

q1 = np.array([[q1x, q1y, f]]).T

print('q1 = \n'+str(q1))

q2x = p2[0][0]*(f/p2[2][0])
q2y = p2[1][0]*(f/p2[2][0])

q2 = np.array([[q2x, q2y, f]]).T

print('q2 = \n'+str(q2))

q1 = 
[[0.01666667]
 [0.03333333]
 [0.05      ]]
q2 = 
[[0.00563257]
 [0.01133743]
 [0.05      ]]


---
### D)

In [21]:
sx = 640/(0.0006*640) # ???
sy = 480/(0.00048*480) # ???
u0 = 0
v0 = 0

A = np.array([[f*sx, 0, u0], [0, f*sy, v0], [0, 0, 1]])

q1_hat = np.floor(1/f*(np.matmul(A,q1)))

print('q1_hat = \n'+str(q1_hat))

q2_hat = np.floor(1/f*(np.matmul(A,q2)))

print('q2_hat = \n'+str(q2_hat))

q1_hat = 
[[27.]
 [69.]
 [ 1.]]
q2_hat = 
[[ 9.]
 [23.]
 [ 1.]]


---
### E)

In [22]:
A_inv = np.linalg.inv(A)

p1_rec = np.matmul(A_inv,q1_hat)*p1[2][0]

p2_rec = np.matmul(A_inv,q2_hat)*p2[2][0]

print('p1_rec.T = \n'+str(p1_rec.T))

print('p2_rec.T = \n'+str(p2_rec.T))

mean_reprojection_error = 0.5*(np.linalg.norm(p1 - p1_rec)+np.linalg.norm(p2 - p2_rec))

print('mean_reprojection_error = '+str(mean_reprojection_error))

error_p1 = np.linalg.norm(p1 - p1_rec)
error_p2 = np.linalg.norm(p2 - p2_rec)

p1_rec.T = 
[[0.972  1.9872 3.    ]]
p2_rec.T = 
[[ 1.93810103  3.96233988 17.94537989]]
mean_reprojection_error = 0.08314815397361305


In [23]:
print('    p1.T = '+str(p1.T))

print('p1_rec.T = '+str(p1_rec.T))

print('\nerror_p1 = '+str(error_p1))

print('\n    p2.T = '+str(p2.T))

print('p2_rec.T = '+str(p2_rec.T))

print('\nerror_p2 = '+str(error_p2))

print('\nMean Reprojection Error  = '+str("{:.3f}".format(mean_reprojection_error)))

    p1.T = [[1 2 3]]
p1_rec.T = [[0.972  1.9872 3.    ]]

error_p1 = 0.030787010247830548

    p2.T = [[ 2.02157298  4.06908819 17.94537989]]
p2_rec.T = [[ 1.93810103  3.96233988 17.94537989]]

error_p2 = 0.13550929769939557

Mean Reprojection Error  = 0.083
