In [68]:
# @toffanetto

from sympy import *
import numpy as np


Dado os ângulos de rotação nos eixos x, y e z como x, y e z, têm-se as rotações que levam do frame {2} para o frame {1}:

In [69]:
x, y, z = symbols("x y z")

Rx = np.array([[1, 0, 0], [0, cos(x), sin(x)], [0, -sin(x), cos(x)]])
print('Rx = \n'+str(Rx))

Ry = np.array([[cos(y), 0, -sin(y)], [0, 1, 0], [sin(y), 0, cos(y)]])
print('Ry = \n'+str(Ry))

Rz = np.array([[cos(z), sin(z), 0], [-sin(z), cos(z), 0], [0, 0, 1]])
print('Rz = \n'+str(Rz))

Rx = 
[[1 0 0]
 [0 cos(x) sin(x)]
 [0 -sin(x) cos(x)]]
Ry = 
[[cos(y) 0 -sin(y)]
 [0 1 0]
 [sin(y) 0 cos(y)]]
Rz = 
[[cos(z) sin(z) 0]
 [-sin(z) cos(z) 0]
 [0 0 1]]


In [70]:
R_1_2 = np.matmul(Rz,np.matmul(Ry,Rx))
print('R_(1/2) = \n'+str(R))

R_(1/2) = 
[[cos(y)*cos(z) sin(x)*sin(y)*cos(z) - sin(z)*cos(x)
  sin(x)*sin(z) + sin(y)*cos(x)*cos(z)]
 [sin(z)*cos(y) sin(x)*sin(y)*sin(z) + cos(x)*cos(z)
  -sin(x)*cos(z) + sin(y)*sin(z)*cos(x)]
 [-sin(y) sin(x)*cos(y) cos(x)*cos(y)]]


Dado os ângulos de rotação nos eixos x, y e z como x, y e z, têm-se as rotações que levam do frame {1} para o frame {2}:

In [71]:
Rx = Rx.T
Ry = Ry.T
Rz = Rz.T

R_2_1 = np.matmul(Rz,np.matmul(Ry,Rx))
print('R_(2/1) = \n'+str(R))

R_(2/1) = 
[[cos(y)*cos(z) sin(x)*sin(y)*cos(z) - sin(z)*cos(x)
  sin(x)*sin(z) + sin(y)*cos(x)*cos(z)]
 [sin(z)*cos(y) sin(x)*sin(y)*sin(z) + cos(x)*cos(z)
  -sin(x)*cos(z) + sin(y)*sin(z)*cos(x)]
 [-sin(y) sin(x)*cos(y) cos(x)*cos(y)]]
