### B)

In [1]:
# toffanetto

import numpy as np

In [2]:
class tf:
    def __init__(self, x, y, z, phi, theta, psi):
        self.x = x
        self.y = y
        self.z = z 
        self.phi = np.deg2rad(phi)
        self.theta = np.deg2rad(theta)
        self.psi = np.deg2rad(psi)
        
        self.t = np.array([[x, y ,z]]).T
        
    def getPoint(self,p1):
        Rx = np.array([[1, 0, 0], [0, np.cos(self.psi), np.sin(self.psi)], [0, -np.sin(self.psi), np.cos(self.psi)]])
        Ry = np.array([[np.cos(self.theta), 0, -np.sin(self.theta)], [0, 1, 0], [np.sin(self.theta), 0, np.cos(self.theta)]])
        Rz = np.array([[np.cos(self.phi), np.sin(self.phi), 0], [-np.sin(self.phi), np.cos(self.phi), 0], [0, 0, 1]])
        R = np.matmul(Rz,np.matmul(Ry,Rx))
        
        p2 = np.matmul(R,p1) + self.t
        return p2

In [3]:
p1 = np.array([[0.03, -0.01, 30]]).T

p1_to_p2_TF = tf(x=0.01, y=-0.02, z=-0.3, phi=2, theta=1, psi=2)

p2 = p1_to_p2_TF.getPoint(p1=p1)
print('p2 = \n'+str(p2))

p2 = 
[[-0.44677296]
 [ 1.03357395]
 [29.67803096]]


---
### C)

In [4]:
f = 0.01

q1x = p1[0][0]*(f/p1[2][0])
q1y = p1[1][0]*(f/p1[2][0])

q1 = np.array([[q1x, q1y, f]]).T

print('q1 = \n'+str(q1))

q2x = p2[0][0]*(f/p2[2][0])
q2y = p2[1][0]*(f/p2[2][0])

q2 = np.array([[q2x, q2y, f]]).T

print('q2 = \n'+str(q2))

q1 = 
[[ 1.00000000e-05]
 [-3.33333333e-06]
 [ 1.00000000e-02]]
q2 = 
[[-0.00015054]
 [ 0.00034826]
 [ 0.01      ]]


---
### D)

In [5]:
M = 640
N = 480
Lx = 0.0006
Ly = 0.00048

sx = M/Lx
sy = N/Ly
u0 = np.floor(M/2)
v0 = np.floor(N/2)

print('sx = '+str(sx))
print('sy = '+str(sy))
print('u0 = '+str(u0))
print('v0 = '+str(v0))

A = np.array([[f*sx, 0, u0], [0, f*sy, v0], [0, 0, 1]])

q1_hat = np.floor(1/f*(np.matmul(A,q1)))

print('q1_hat = \n'+str(q1_hat))

q2_hat = np.floor(1/f*(np.matmul(A,q2)))

print('q2_hat = \n'+str(q2_hat))

sx = 1066666.6666666667
sy = 1000000.0
u0 = 320.0
v0 = 240.0
q1_hat = 
[[330.]
 [236.]
 [  1.]]
q2_hat = 
[[159.]
 [588.]
 [  1.]]


---
### E)

In [6]:
A_inv = np.linalg.inv(A)

p1_rec = np.matmul(A_inv,q1_hat)*p1[2][0]

p2_rec = np.matmul(A_inv,q2_hat)*p2[2][0]

print('p1_rec.T = \n'+str(p1_rec.T))

print('p2_rec.T = \n'+str(p2_rec.T))

mean_reprojection_error = 0.5*(np.linalg.norm(p1 - p1_rec)+np.linalg.norm(p2 - p2_rec))

print('mean_reprojection_error = '+str(mean_reprojection_error))

error_p1 = np.linalg.norm(p1 - p1_rec)
error_p2 = np.linalg.norm(p2 - p2_rec)

# Therefore, the uncertainty is +/- 0.5 pixel, then:
error_p1_theoric = np.matmul(A_inv,np.array([[0.5, 0.5, 0]]).T)*p1[2][0]
error_p2_theoric = np.matmul(A_inv,np.array([[0.5, 0.5, 0]]).T)*p2[2][0]

p1_rec.T = 
[[ 2.8125e-02 -1.2000e-02  3.0000e+01]]
p2_rec.T = 
[[-0.44795278  1.03279548 29.67803096]]
mean_reprojection_error = 0.002077483487965252


In [7]:
print('    p1.T = '+str(p1.T))

print('p1_rec.T = '+str(p1_rec.T))

print('\nerror_p1 = '+str(error_p1))

print('\n error_p1_theoric = \n'+str(error_p1_theoric))

print('\n    p2.T = '+str(p2.T))

print('p2_rec.T = '+str(p2_rec.T))

print('\nerror_p2 = '+str(error_p2))

print('\nerror_p2_theoric = \n'+str(error_p2_theoric))

print('\nMean Reprojection Error  = '+str("{:.4f}".format(mean_reprojection_error)))

print('\nUncertain norm = '+str("{:.4f}".format(np.linalg.norm(error_p1_theoric))))

    p1.T = [[ 3.e-02 -1.e-02  3.e+01]]
p1_rec.T = [[ 2.8125e-02 -1.2000e-02  3.0000e+01]]

error_p1 = 0.0027414640249326687

 error_p1_theoric = 
[[0.00140625]
 [0.0015    ]
 [0.        ]]

    p2.T = [[-0.44677296  1.03357395 29.67803096]]
p2_rec.T = [[-0.44795278  1.03279548 29.67803096]]

error_p2 = 0.0014135029509978352

error_p2_theoric = 
[[0.00139116]
 [0.0014839 ]
 [0.        ]]

Mean Reprojection Error  = 0.0021

Uncertain norm = 0.0021
